#!/bin/sh

#################################################################
# zyconfig
# Pengguowen <linux@zlgmcu.com>
# service autoboot config  script
# 2011/5/5
#################################################################
PROGRAM=zyconfig
PATH=/bin:/sbin:/usr/bin:/usr/sbin

is_ignored_file() {
    case "$1"  in
        skeleton | README | rc | rcS | reboot | functions | template )
            return 0
        ;;
    esac
    return 1
}

usage() {
    echo "usage:"
    echo "          ${PROGRAM}  -l|--list                                                 (show all service status)"
    echo "          ${PROGRAM}  -a|--add [service_names]                                  (add a service to autoboot)"
    echo "          ${PROGRAM}  -d|--del [service_names]                                  (delete a service form autoboot list)"
    echo "          ${PROGRAM}  -c|--cal [service_names]                                  (cal a service form autoboot list)"
    echo "          ${PROGRAM}  -n|--new [serivice_name] [level] [path/to/program] [args] (add a usr program to autoboot)"
    echo "          ${PROGRAM}  -h|--help                                                 (print this message)"
    echo "          ${PROGRAM}  -v|--version                                              (print verson of this tool)"
}


VERSION="`basename $0` ver. 0.1"
SERVICEDIR="/etc/init.d"
OPTIONS=
SERVICE=

cd ${SERVICEDIR}
if [ $# -eq 0 ]; then
    usage
    exit 0
fi

case "${1}" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        echo ${VERSION}
        exit 0
    ;;
    --list|-l)
        echo -e  "Service\t\t\tLevel\t\t\tStatus"
        for SERVICE in * ; do
            Level=${SERVICE:1:2}
            if ! is_ignored_file "${SERVICE}"; then
                if [[ ${Level} -lt 50 ]];then
                    continue
                fi
                if [[ ${SERVICE:0:1 } = "S" ]]; then
                    echo  -e "${SERVICE#*[0-9][0-9]}\t\t\t${Level}\t\t\ton"
                elif [[ ${SERVICE:0:1 } = "T" ]]; then
                    echo  -e "${SERVICE#*[0-9][0-9]}\t\t\t${Level}\t\t\toff"
                else
                    continue
                fi
            fi
        done
    ;;
    --add|-a)
        if [[ $# -ne 2 ]]; then
            usage
            exit 0
        fi
        added=0;
        for SERVICE in * ; do
            Level=${SERVICE:1:2}
            if ! is_ignored_file "${SERVICE}"; then
                if [[ ${Level} -lt 50 ]];then
                    continue
                fi
                if [[ "${SERVICE:0:1}" != "T" ]];then
                    continue
                else
                    if [[ "${SERVICE#T[0-9][0-9]}" = "${2}" ]]; then
                        mv "${SERVICE}" "S${SERVICE#T}"
                        added=1
                        break;
                    fi
                fi
            fi
        done
        if [[ ${added} -eq 1 ]]; then
            echo "${SERVICE} have been add to autoboot list"
        else
            echo "service name error!";
        fi
    ;;
    --del|-d)
        if [[ $# -ne 2 ]]; then
            usage
            exit 0
        fi
        deled=0;
        for SERVICE in * ; do
            Level=${SERVICE:1:2}
            if ! is_ignored_file "${SERVICE}"; then
                if [[ ${Level} -lt 50 ]];then
                    continue
                fi
                if [[ "${SERVICE#*[0-9][0-9]}" = "${2}" ]]; then
                    rm "${SERVICE}" 
                    deled=1
                    break;
                fi
            fi
        done
        if [[ ${deled} -eq 1 ]]; then
            echo "${SERVICE} have been delete from autoboot list"
        else
            echo "service name error!";
        fi

    ;;
    --cal|-c)
        if [[ $# -ne 2 ]]; then
            usage
            exit 0
        fi
        caled=0;
        for SERVICE in * ; do
            Level=${SERVICE:1:2}
            if ! is_ignored_file "${SERVICE}"; then
                if [[ ${Level} -lt 50 ]];then
                    continue
                fi
                if [[ "${SERVICE:0:1}" != "S" ]];then
                    continue
                else
                    if [[ "${SERVICE#S[0-9][0-9]}" = "${2}" ]]; then
                        mv "${SERVICE}" "T${SERVICE#S}"
                        caled=1
                        break;
                    fi
                fi
            fi
        done
        if [[ ${caled} -eq 1 ]]; then
            echo "${SERVICE} have been cannel from autoboot list"
        else
            echo "service name error!";
        fi

    ;;
    --new|-n)
        if [[ $# -lt 4 ]]; then
            usage
            exit 0
        fi

        if [[ -n "${3/9[0-9]/}" ]];then
            echo "level must between 90~99"
            exit 0
        fi

        NAME="S${3}${2}"
        if [[ $# -eq 4 ]]; then
            cat skeleton | sed "s/BIN=/BIN=${2}/g"| sed "s:BIN_PATH=:BIN_PATH=$4:g"  >  $NAME
        else
            cat skeleton |  sed "s/BIN=/BIN=${2}/g" | sed "s:BIN_PATH=:BIN_PATH=$4:g" > template 
            shift 4
            BIN_ARGS=$@
            cat template | sed "s:ARGS=:ARGS='$BIN_ARGS':g" > $NAME
            rm -fr template
        fi
        chmod +x $NAME
    ;;
esac
sync
exit 0
