#! /bin/sh

set -e

DESC="vsftpd"
NAME=vsftpd
DAEMON=/usr/sbin/$NAME

CONF_USER=/opt/etc/vsftpd.conf
CONF_SYS=/etc/vsftpd.conf
CONF_FILE=${CONF_USER}

if [ ! -f ${CONF_USER} ];then
    CONF_FILE=${CONF_SYS}
fi

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -b -x $NAME ${CONF_FILE}
	echo "OK"
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x $NAME
	echo "OK"
	;;
  restart|force-reload)
	echo "Restarting $DESC: "
	$0 stop
	sleep 1
	$0 start
	echo ""
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
